"""Problem 1 of the machine-code chapter — write the C that produces this.

Here is a function's disassembly. Write a C function that compiles to the same instructions.

Not *similar* instructions — the same ones, in the same order. The test compiles what you write
at the same optimisation level and compares the mnemonics, so a function that computes the right
answer by another route does not pass. Reconstructing behaviour is easy; reconstructing the
compiler's route to it is the exercise.

The listing is generated by the test from this repository's own toolchain, so it is the one your
compiler produces rather than one transcribed from somewhere.
"""

from __future__ import annotations

#: The signature to keep. Only the body is yours.
SIGNATURE = "long reader_target(long a, long b)"

#: Your reconstruction: the whole function, including the signature above.
RECONSTRUCTION = """
long reader_target(long a, long b) {
  /* Problem 4.1 — see the Problems section of the machine-code chapter. */
  return 0;
}
"""
